# Generated by Django 4.2.10 on 2024-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoguardian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Air Pollution', 'Air Pollution'), ('Water Pollution', 'Water Pollution'), ('Soil Pollution', 'Soil Pollution'), ('Noise Pollution', 'Noise Pollution'), ('Animal Endangerment', 'Animal Endangerment'), ('Disastrous Weather', 'Disastrous Weather'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
