# Generated by Django 5.0.2 on 2024-03-18 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoguardian", "0002_incidentcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("evidence", models.FileField(upload_to="evidence/")),
                (
                    "incident_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecoguardian.incidentcategory",
                    ),
                ),
            ],
        ),
    ]
