# Generated by Django 5.0.2 on 2024-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoguardian", "0003_incidentreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="New",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="user",
            field=models.CharField(default="Anonymous User", max_length=255),
        ),
    ]
