# Generated by Django 5.0.2 on 2024-03-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoguardian", "0004_incidentreport_status_incidentreport_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="admin_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
