# Generated by Django 5.0.2 on 2024-04-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoguardian", "0005_incidentreport_admin_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentreport",
            name="evidence",
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="evidence/")),
                (
                    "incident_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="ecoguardian.incidentreport",
                    ),
                ),
            ],
        ),
    ]
